# ============================================================
# DOS MAQUINAS - esta es la B, la que se conecta a la A
#
#   dosbox -conf dosbox-red-b.conf
#
# CAMBIA DOS COSAS en este fichero:
#   1. la ruta de los "mount", a donde tengas el juego EN ESTA maquina
#   2. la IP del "ipxnet connect", que es la de la maquina A
#
# Arranca esta DESPUES de la A.
# ============================================================

[dosbox]
machine=svga_s3

[cpu]
core=auto
# Los mismos ciclos que la maquina A. Sin excepcion.
cycles=fixed 30000

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5

[ipx]
ipx=true

[autoexec]
# <<< CAMBIA ESTAS DOS RUTAS por las de esta maquina >>>
mount c C:\CutreGameMSDOS
mount k C:\CutreGameMSDOS\net-test\log-b
# <<< CAMBIA ESTA IP por la de la maquina A >>>
ipxnet connect 192.168.1.45
c:
cd \bin
game.exe /net
